# Generated by Django 5.2.3 on 2025-07-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='time_close',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='time_open',
            field=models.TimeField(),
        ),
    ]
