# Generated by Django 5.2.3 on 2025-07-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='house',
            field=models.IntegerField(max_length=255),
        ),
    ]
